sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 111.229.128.159
    port: 3306
    database: sky_take_out
    username: root
    password: wyc121815
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tA52PTCeZZ5A5Qt5gFh
    access-key-secret: biL6MCuE4m0KmO7SbaHHFZ8SARI6qh
    bucket-name: wei-tlais
  redis:
    host: localhost
    port: 6379
    password: wyc121815
    database: 0
  wechat:
    appid: wxa2706dd4316947ca
    secret: 3526f44fff50d867e3bb58bb4a3cad94
#    虚假数据
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php